[project]
name = "py"
version = "0.1.0"
description = ""
readme = "readme.md"
requires-python = ">=3.13"
dependencies = [
    "pydantic>=2.10.6",
    "python-dotenv>=1.0.0",
]

[dependency-groups]
dev = ["ruff>=0.9.4"]
